LEAGUES = {
    "ENG": {
        "label": "Premier League (ENG)",
        "csv_url": "https://www.football-data.co.uk/mmz4281/2526/E0.csv",
        "csv_suffix": "(ENG)",
        "fd_comp": "PL",
        "aliases": {
            "man city": "Manchester City FC",
            "man united": "Manchester United FC",
            "nott'm forest": "Nottingham Forest FC",
            "nottingham forest": "Nottingham Forest FC",
            "west ham": "West Ham United FC",
            "tottenham": "Tottenham Hotspur FC",
            "brighton": "Brighton & Hove Albion FC",
            "bournemouth": "AFC Bournemouth",
            "wolves": "Wolverhampton Wanderers FC",
            "newcastle": "Newcastle United FC",
            "leeds": "Leeds United FC",
            "aston villa": "Aston Villa FC",
            "everton": "Everton FC",
            "fulham": "Fulham FC",
            "brentford": "Brentford FC",
            "crystal palace": "Crystal Palace FC",
            "liverpool": "Liverpool FC",
            "arsenal": "Arsenal FC",
            "chelsea": "Chelsea FC",
            "burnley": "Burnley FC",
            "sunderland": "Sunderland AFC",
        },
    },
    "SPA": {
        "label": "La Liga (SPA)",
        "csv_url": "https://www.football-data.co.uk/mmz4281/2526/SP1.csv",
        "csv_suffix": "(SPA)",
        "fd_comp": "PD",
        "aliases": {
            "ath bilbao": "Athletic Club",
            "athletic bilbao": "Athletic Club",
            "atletico": "Atlético de Madrid",
            "atm": "Atlético de Madrid",
            "real sociedad": "Real Sociedad de Fútbol",
            "barcelona": "FC Barcelona",
            "real madrid": "Real Madrid CF",
            "valencia": "Valencia CF",
            "sevilla": "Sevilla FC",
            "villarreal": "Villarreal CF",
            "betis": "Real Betis Balompié",
            "celta": "RC Celta de Vigo",
            "rayo": "Rayo Vallecano de Madrid",
            "osasuna": "CA Osasuna",
            "getafe": "Getafe CF",
            "alaves": "Deportivo Alavés",
            "mallorca": "RCD Mallorca",
            "girona": "Girona FC",
            "las palmas": "UD Las Palmas",
            "leganes": "CD Leganés",
            "cadiz": "Cádiz CF",
            "granada": "Granada CF",
        },
    },
}
